### ISSUE TITLE
Index button is not recognized

### ISSUE THREAD

**Issue by ChenPENGPENGcpp** [Megasteakman/MegaMocapVR#17]
Your project is really exciting. I Can’t wait to use it. But I’ve run into some problems, and I was hoping you could help me.

![屏幕截图 2021-12-21 162744](https://user-images.githubusercontent.com/94383778/146921627-f852d92f-0ded-45d0-9c1b-008679221bd1.png)
VRMocap_PlayerPawn_BP  compiled with these warnings in the picture.
And I can’t use any index controller button at run time.

But in this empty project, BP compiled without warning https://www.dropbox.com/s/trdhmvlpp45ozgr/VRMocap_427.rar?dl=0

I followed the settings in your youtube video, and I don’t know what I missed.

btw,Thanks again for the project

**Comment by Megasteakman** [comment]
That error means the project settings don't have those input bindings added.  You can see the process of adding input bindings to your project here: https://youtu.be/crv6AIbadSo?t=666

You also have to make sure you click into the viewport when you enter play mode to ensure the game instance will receive your input.  Failing that, I included a node near the end of the beginplay logic on the player pawn that will calibrate automatically after 15 seconds if you hook that up.  I hope that helps!

**Comment by ChenPENGPENGcpp** [comment]
> That error means the project settings don't have those input bindings added. You can see the process of adding input bindings to your project here: https://youtu.be/crv6AIbadSo?t=666
> 
> You also have to make sure you click into the viewport when you enter play mode to ensure the game instance will receive your input. Failing that, I included a node near the end of the beginplay logic on the player pawn that will calibrate automatically after 15 seconds if you hook that up. I hope that helps!

Thanks！This was a complete oversight on my part because I was using UE4.27 and didn’t watch the UE5 tutorial video.

I’m sorry to take up your time with such a basic question. 
btw,Wondering if you’re gonna open a discord channel in https://discord.com/
This may allow users to help each other instead of bothering you with every problem.

**Comment by Megasteakman** [comment]
I just made a discord: this link will only work for 7 days though: https://discord.gg/vajKSxnb

I'm trying to figure out a way to post a permanent link without getting lots of spam bots, so let me know if you have any ideas there.
