### ISSUE TITLE
❤️ Would love to help

### ISSUE THREAD

**Issue by tljstewart** [Megasteakman/MegaMocapVR#25]
Hey Kyle, this phenomenal stuff. Would love to pitch in where I can. Maybe we can setup sometime to chat about the project [me@tljstewart.ai](mailto:me@tljstewart.ai)

**Comment by Megasteakman** [comment]
Hey, thanks so much, that's really kind of you!  I am in a bit of the a holding pattern as UE5 preview 2 broke live link xr for me, but I think once the next version is released there's some new features I would like to add.  Unfortunately I am going on vacation very soon, so not sure when I will be able to talk, but I'll try to stay active in our discord: https://discord.gg/YNdVfDRU

**Comment by ibrews** [comment]
Discord invite broken! I'd be thrilled to chat as well-- I've been playing with the new Vive SDK that gets mouth and eye tracking working on a MetaHuman, and I'd love to work with you on connecting it into your system.

**Comment by Megasteakman** [comment]
Sorry the link was broken: I thought I chose a link that never expired, but it looks like I didn't.  Try this one out: https://discord.gg/M32fp5Cb3K
