### ISSUE TITLE
Strange character deformation for models imported from Vroid

### ISSUE THREAD

**Issue by michaeljyang** [Megasteakman/MegaMocapVR#27]
Hi there,

First of all, really appreciate you for this project. I got to mocap working with the examples. However, when I imported a model made with Vroid (https://vroid.com/en/studio), the character became very strange. 

This is the great result I got with the “SK_Mannequin_Mobile” skeleton mesh:
![6f1ed7cf26e0763819c52844b4ade14](https://user-images.githubusercontent.com/41892892/186619295-8ffdf460-9117-49a6-b7fc-f1a258169698.jpg)

So after I got good results with the “SK_Mannequin_Mobile” skeleton mesh, I changed the skeleton mesh in my character blueprint to a ue4mannequin type that showed up when I imported my vroid model with a plugin called VRM4U (https://github.com/ruyo/VRM4U/releases). 

This is how my model should have looked like:
![image](https://user-images.githubusercontent.com/41892892/186617961-13ba9f7e-7bba-4bf5-aa7f-0e52f1eee1e9.png)

Then I re-assigning the skeleton to "SK_Mannequin_Mobile_Skeleton" in the MMVR file which lead to the following results.

This is how it turned out after re-assigning the skeleton to "SK_Mannequin_Mobile_Skeleton" in the MMVR file:
![559443d3dc2b34edc6f14fd505db0c9](https://user-images.githubusercontent.com/41892892/186619068-1a41594a-5963-41e6-85f6-4c3e7255b81c.jpg)

I'm not sure what is wrong with the skeleton. Would you please have a look at this and give me some advice? Thank you very much.

I'm using Unreal 5.03, vive trackers.
The model file I imported from vroid is this one:
[Anya Forger.zip](https://github.com/Megasteakman/MegaMocapVR/files/9423131/Anya.Forger.zip)

**Comment by michaeljyang** [comment]
I also tried to follow the chapter about the strange deformation for metahumans. However, I'm not sure if i did it wrong but it didn't work for me.

**Comment by Megasteakman** [comment]
Do your bone axis alignments also match the UE4 mannequin?  I'm using some bone orientations in the set up and IK solver phases, so it they aren't the same there could be really unpredictable results.  If the orientations are different, I think this would be a good use-case for the IK retargeting actor profile: https://www.youtube.com/watch?v=ZBv5qi4GJDk&t=734s

**Comment by michaeljyang** [comment]
I actually have another question about finger tracking. I could only manage to get three fingers moving on each hand. My thumb and index finger weren't able to be tracked. Any guess what may have caused this?

**Comment by Megasteakman** [comment]
Yeah, the fact that the joints were mismatched is probably another problem.

Not sure why your fingers aren't working.  The index is a little imprecise, and I find somehow I have to drum my fingers back and forth to get it working.

**Comment by michaeljyang** [comment]
OMG! IK retargeting works! I got my model to move! THANK YOU SO MUCH!

 I have another question about the facial expressions. Does VRM imported models support facial expression? Or could I make some presets and get them to work in unreal?

**Comment by Megasteakman** [comment]
Hmm, I actually don't know how that works for other people: I think they use a lot of external apps to drive those?  I did include a retargeting asset template in the project so you can make the AR Kit stuff remap to whatever blendshapes you want, but you may have to hard code the live link phone name into your characters anim bp and use that retargeting asset in there.

**Comment by michaeljyang** [comment]
Ok thanks man. That sounds a little bit to difficult for me now. By the way, I had some problems with the inputs of my index controllers. During calibration, I could rotate the target mesh but when I wanted to move it with my left controller it could only go oneway. Did this occur to you? Also, the controller inputs would just not work for sometimes. I need to restart the project/steam vr to get them working again.

**Comment by Megasteakman** [comment]
For inputs, you can try running the project in vr mode before you try running it in normal game mode, or flipping some of the input setting back and forth in project settings (change the setting from the correct button mapping to an incorrect one and back).  Also, turning on the controllers before the trackers can help (sometimes the trackers assume the roles of controllers and steal their inputs).

I'm sure there's some kind of VRM face tutorial on youtube: I just haven't implemented them because I don't typically use those models and don't want to rely on anything outside of unreal engine for the project to work.

**Comment by michaeljyang** [comment]
Really appreciate your time and patience. For the trackers stealing controller part, I figured out that adding trackers first in live link then check the controllers would help : )
