### ISSUE TITLE
Problem with baking facial animation to control rig 

### ISSUE THREAD

**Issue by Zacharydpberry** [Megasteakman/MegaMocapVR#29]
Hey, 

Really enjoyed using your plugin so far. I've been trying to bake the facial animation from a capture to the face control rig in sequencer and unfortunately its not baking any of the individual keyframes. I was wondering if you had a fix to this ? 

Would really appreciate the help.

All the best, 

Zak

**Comment by Megasteakman** [comment]
Unfortunately I've never baked to the metahuman face rig before, sorry!  Closing this as it seems outside the scope of MMVR.
