### ISSUE TITLE
List of face capture devices

### ISSUE THREAD

**Issue by luoxz-ai** [Megasteakman/MegaMocapVR#30]
![image](https://user-images.githubusercontent.com/17875098/196579564-69cc69ea-1c63-4884-9138-7ca78ee56aa8.png)

What is the name of this accessory, where to buy it, I have found the source of other equipment

**Comment by Megasteakman** [comment]
It's the Glide Gear POV 100.  Ultimately I wouldn't recommend it as it is very heavy and will cause huge neck strain or worse (have to be careful with helmets, and definitely don't do anything acrobatic with them).  Right now I am using the standard deviation iphone hmc, and it's much better.  Personally I think it is worth the price, but it is a very large leap up.
