### ISSUE TITLE
Add a few more trackers

### ISSUE THREAD

**Issue by Zigmunt** [Megasteakman/MegaMocapVR#32]
Hello there! Is there any possibility to hear from you a brief guide how to add a pair of additional trackers to your setup. For example, we want to add 2 trackers for the shoulders and 2 trackers for the knees. We want to try it on our own, and it would be nice to here some thoughts from you. Thanks in advance.

**Comment by Megasteakman** [comment]
Hey!  So this is a VERY big change that would require a lot of work, and I think very minimal gains.  It's possible, but you would have to add additional fields to the live link tracker names struct, create logic for determining if those are working, transfer that information to 5 different animbps (or the ones you want) and then change the control rig for whatever character you are interested it.  If someone wants to make these changes and submit them I could take a look, but I don't think I can invest time on this.  Also, I have noticed, going above 10 trackers causes a lot more drop-out and interference, so I'm not sure more trackers is the best way forward unless you are using something like antilatency.
