### ISSUE TITLE
UE5 Not reading .uasset

### ISSUE THREAD

**Issue by Dcgoodash** [Megasteakman/MegaMocapVR#33]
In file explorer I see the .uasset files, however they are not coming up in UE5, A few are, But most of them are not. How to do i get UE5 to read them?

**Comment by Megasteakman** [comment]
Did you download the github branch that matches your engine version?  Every commit should start with what version of the engine I tested/submitted for.  The main branch is currently 5.1.1, so if you aren't on that version you will have to chose an older commit.

**Comment by Dcgoodash** [comment]
Sorry, New to all this, you are correct, I was opening it in my 5.0 editor not 5.1. Thank you
