### ISSUE TITLE
Does this require a headset? If so, which are compatible?

### ISSUE THREAD

**Issue by SuperNatendo** [Megasteakman/MegaMocapVR#34]
Hi there Megasteakman,

Firstly I'd like to say thank you for creating this project. I'm relatively new to unreal but understand enough to realize what a fantastic addon this is! I'm looking to get into doing my own animating using your project and wanted to know if it's possible to run this on unreal without a headset? If not, which headsets should be compatible? I recently purchased 2 index controllers, 7 trackers and 2 base stations but seem to have trouble getting this working and assume it's due to not having an index or vive headset and wanted to know what my options would be since vive VR is all new to me! Thank you in advance!

**Comment by bencompton** [comment]
I believe this is a duplicate issue, and should probably be closed in favor of #14. TL;DR: it appears from that issue that using this project with no HMD is possible (haven't tested myself). I initially wanted to use this with an HMD for head tracking to save buying an additional tracker, but as I mentioned [here](https://github.com/Megasteakman/MegaMocapVR/issues/35#issuecomment-1496325447), I changed my mind and appreciate that MMVR has a non-VR UI. IMO, if you don't already own a headset, don't need one for other uses, and can get it working without the HMD, then there isn't really a reason to buy one.
