### ISSUE TITLE
Metahuman not moving after calibration

### ISSUE THREAD

**Issue by bencompton** [Megasteakman/MegaMocapVR#35]
# What Happened

When I press play, line up the on-screen widgets for my trackers with a Metahuman, and press both B buttons to complete calibration, I hear the chime and the camera view changes, but the Metahuman does not move with the trackers.

# Expectation

When I line up the widgets with my character and press both B buttons, I will assume control of the character.

# Additional Info

**UE version:** 5.1.1
**MMVR Version**: b34c338bdc9e4b82e793593b3fd1355d6033d40c

**Tracker setup**:

* Valve Index HMD for head tracking
* Valve Index controllers for hand tracking
* 3 Vive 3.0 trackers (pelvis, left foot, right foot)

Is this setup supported? For example, the videos show a chest and a head tracker, whereas I am using the HMD for the head and no chest tracker. I am also using no elbow trackers. In addition, I wasn't able to find a way to null out the trackers I don't have in  `Live Link Tracker Set Struct`, and left the default, bogus tracker IDs set for the chest and elbows.

Edit: I have a 4th tracker that I tested first as a head tracker and then as a chest tracker, but same result in both cases. Perhaps it will only work with both?

**Verified the following**:

* Not in simulation mode
* Metahuman has a rotation of `-90` on the Z axis so it faces towards the positive X axis (rotation set on the Metahuman Body component in the Details pane)
* PlayerPawn `Live Link Tracker Set Struct` is configured with the correct tracker IDs, including the Index Controllers, Index HMD for both `VR_HMD` and `HeadTracker`, and trackers for feet and pelvis.
* With `Debug Strings HUD On`, see no error messages during the process
* The Metahuman BP has a MMVR_Mocap_Actor_Component. In the Details pane, this component has `Is Mocap Target` set to true, `Player Index` is 0 (matches PlayerPawn), and `Mocap Actor Rig Enum` is Metahuman.

**Comment by Megasteakman** [comment]
Thanks so much for the thorough trouble shooting!  I spent a few minutes trying to recreate this set up since it's been a while since I have used the VR HMD for captures, and it does work (but I definitely didn't line up my height correctly).  I think the problem might be that you have to run in VR mode to get hmd movement, and the head is one of the most important trackers in the whole system (at least that is my guess).  

I made a video of me running through a quick set up tonight: let me know if this helps: https://www.youtube.com/watch?v=Pkt2TR04PYA

Also, if you end up getting weird deformations, check these steps: https://github.com/Megasteakman/MegaMocapVR/wiki#fixing-strange-character-deformation-metahumans-etc
There's a weird bug where control rig will use the preview skeleton to set up the rig logic, and it messes with the various aims and fake trackers I set up a lot.

**Comment by bencompton** [comment]
Wow, first time I've ever gotten a video response to a GitHub issue! Thank you so much for taking the time to provide such a detailed and informative response, @Megasteakman!

Around 30 seconds into your video, I was slapping my forehead because it appears I forgot to double check `Animation Class` for the body and face. I had set it in a previous iteration, then I started from scratch to work through another issue, but forgot to configure it the second time around.

I was initially planning to use my 4th tracker as a chest tracker with the HMD for head tracking, but after following your video to get it setup, it’s pretty clear that using it as a head tracker and going HMD-less is a better idea. I actually appreciate that MMVR’s focus is providing a solid non-VR UI that can be operated with a controller when doing face capture, which definitely is a better UX than other tools that have clunky VR-based UIs (not naming any names). Not to mention, a fully wireless setup is way nicer. For those reasons, not sure it’s really worth investing in making MMVR work better with HMDs.

As a side note for future maintainability, would it be possible to add `None` to the dropdown so it's not necessary to delete the text before a `None` option appears? IMO, `None` would ideally be the default instead of pre-populating with tracker ids.

Anyhow, thanks again for helping me pinpoint the problem! Closing this issue, and am happy to create another issue for the dropdown `None` option if you think can / should be done.

**Comment by ethanporcaro** [comment]
I had this exact same issue, and setting the animation class fixed it. Here is a screenshot for future people

<img width="662" alt="Image" src="https://github.com/user-attachments/assets/319317b7-4587-471b-99b3-338a80773cdd" />

BTW, the walkthrough video is down. If you happen to still have it, I'm sure it would be a great resource
