### ISSUE TITLE
Hello, I also tried your ControlRig, but I found that short people cannot drive Metahuman well. For example, when both arms are straight, the elbow joint is bent. Do you have any good suggestions

### ISSUE THREAD

**Issue by PanDaDerica** [Megasteakman/MegaMocapVR#37]

**Comment by Megasteakman** [comment]
When you calibrate, the system stores your height, and when entering calibrate the system tries to find out the height of the mocap actor and will scale you to match.  Sometimes this does not work perfectly, but you can use the triggers on the VR controllers or on the MMVR Editor Utility Widget to get closer.  You need to match the actor pose as best as possible, making sure the virtual trackers land on the mocap actor in a similar way to how they are on your body.  Sometimes a character's arm length is different however, and in those cases I would visually match characters pose (if they are in an A pose with the elbows bent, yours should be bent.)  You can also turn off the arm calibration helper in the mocap actor component to get more fine control over how your hands are placed, but it's definitely harder to keep both in alignment during the calibration process.

**Comment by PanDaDerica** [comment]
好的 非常感谢 我来尝试一下您说的

**Comment by PanDaDerica** [comment]
Ok, thank you very much. Let me try it out.
