### ISSUE TITLE
Question about Ultra Leap hand tracking support

### ISSUE THREAD

**Issue by timjzee** [Megasteakman/MegaMocapVR#40]
Hi! A while back, in 2b0c7782640b67b07f3866c7c96dd2afa4126f16, you added support for Ultra Leap hand tracking. I'm starting to play around with it, but I think I don't quite understand the workflow for using the Leap Motion controller with MegaMocapVR.

I specified in the mocap actor that I want to use Ultra Leap for hand tracking, but when I press play I automatically go into calibration mode, which requires me to use the controllers.

I'm probably missing something obvious, but could you briefly explain what a Ultra Leap hand tracking workflow would look like in MegaMocapVR?

Thanks a lot!

**Comment by Megasteakman** [comment]
Yeah!  Sorry I haven't been able to make a set up video or documentation for the new features.  You will calibrate with controllers, but you can override the hand data by selecting the Ultra Leap in the Hand Tracking Method,

Also, there is a bool for VTuber mode, which skips entering calibration.  I often use this mode when using an iphone and ultraleap.

Also, there is a BP actor I made for the ultraleap that you can add as a child component to your character so you can get more specific placement of where the sensor is in relation to you (if you don't include that it will spawn in one and attach it to the waist.)

**Comment by timjzee** [comment]
Thanks for the quick response! Good to know about VTuber mode as well!
