### ISSUE TITLE
Unreal 5.2 and 5.3

### ISSUE THREAD

**Issue by kvnbln** [Megasteakman/MegaMocapVR#41]
Greetings sir.  I followed your YouTube video for getting the trackers recognized by UE 5.2 and 5.3 and they worked like a charm.  However, I tried to use the plugin for UE 5.3, and it didn't work.  I'm guessing because its not an official commit of that particular branch.  Am I correct in my assumptions?  Should I just use this for 5.11?  Thank you for all of your help and expertise.

Kevin

**Comment by Megasteakman** [comment]
Oh nice, glad to hear it worked for you.  I came across a problem where setting openXR input in the preferences messed with the trackers, so watch out for that.

I haven't had time to test the changes I made for 5.2, but I didn't do much: just removed anything that was causing errors.  I will post this version if I make sure it is all good: https://www.dropbox.com/scl/fi/vjq81qse9dfyxs16qlzfz/MegaMocapVR_52.zip?rlkey=3z4buinm07yugwv7y72w4t5pl&dl=0

**Comment by pinkybuffalo** [comment]
> Oh nice, glad to hear it worked for you. I came across a problem where setting openXR input in the preferences messed with the trackers, so watch out for that.
> 
> I haven't had time to test the changes I made for 5.2, but I didn't do much: just removed anything that was causing errors. I will post this version if I make sure it is all good: https://www.dropbox.com/scl/fi/vjq81qse9dfyxs16qlzfz/MegaMocapVR_52.zip?rlkey=3z4buinm07yugwv7y72w4t5pl&dl=0

Hi! When i tried to add this files to 5.2 project i have a lot of errors. I thinnk that i dont on someone plugin. Can you check this screenshot and guess what's wrong?
<img width="1910" alt="Screenshot_1" src="https://github.com/Megasteakman/MegaMocapVR/assets/32557526/3f5d2155-247a-436f-b518-562728516b37">

**Comment by Megasteakman** [comment]
@pinkybuffalo Are you using the main branch on github?  I would recommend that over using the older version in dropbox.

Those errors are because you dont have the unreal engine 'ultra leap' plugin installed, which you need if you intend to do hand tracking using an ultraleap.  If you don't need this functionality, you can delete these nodes.  I made anything that needs a plugin like that as modular as possible, so it can be removed (although deleting the whole blueprint asset might causes errors in the player pawn unless you replace it with another blueprint to spawn in).

Hope that helps!

**Comment by kvnbln** [comment]
Not an issue, but just a general question.  Am I able to use this plugin in Unreal 5.3?  Or should I stick to 5.2?

**Comment by Megasteakman** [comment]
@kvnbln Unfortunately I'm trying to get things really solid for 5.2 and haven't been able to bug fix everything on that version, and haven't been able to move on to 5.3.  I'm really hoping to move on to it sometime in the next two weeks, but issues keep cropping up.

That said, in my experience, porting the project is super easy, and mostly just involves looking through the log for any nodes that are throwing up errors.  If the component isn't something major (say the player pawn) then you can often just unplug any nodes that are causing errors (and most errors in my experience are from plugins not being installed in the project).

**Comment by Megasteakman** [comment]
@kvnbln Sorry for the delay: I just put up a 5.3 version of the project.  Let me know if that works for you!
